[package]
name = "rust-api-fetch"
version = "0.1.0"
authors = ["Joshua Byrd <phocks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
